apiVersion: v1
kind: Secret
metadata:
  name: patient-db-secret
  namespace: default
type: Opaque
stringData:
  mongodb-uri: "mongodb+srv://chamudithasanka98_db_user:ugVkuwXjgy2XLv1V@cluster0.gzrwxt7.mongodb.net/patient_db?retryWrites=true&w=majority"