apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: default
  labels:
    app: patient-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5002
    targetPort: 5002
    protocol: TCP
  selector:
    app: patient-service